name: chat_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  socket_io_client: ^2.0.3+1
  json_theme: ^6.4.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
